### ISSUE TITLE
Command block output crashing server | /topoislands new [player]

### ISSUE THREAD

**Issue by Roc496ket** [sam-kirby/topoislands#5]
Hi, can't find the issue template to base my post on, so I'll try to provide as much data as possible to help resolve the issue.

I'm currently setting up a SkyFactory One server for some friends and are having issues with running the /topoislands new [player] command through command blocks. 
![image_2023-03-21_221117587](https://user-images.githubusercontent.com/64569540/226602104-db300201-accb-4b6c-94ab-695a1955b9ff.png)
(there was a pressure plate on this prior)

I had a friend use the command block with the shown command, upon which the server promptly crashed. (I've attached the server crash log) This was using the most recent version of the mod, alongside the mods listed in the crash log. If you need anymore information, please let me know. 

Kind regards,
RamenWombat
[crash-2023-03-21_12.00.16-server.txt](https://github.com/sam-kirby/topoislands/files/11028131/crash-2023-03-21_12.00.16-server.txt)

**Comment by sam-kirby** [comment]
You don't appear to have Topography present on your server; this mod (Topography Islands) cannot function without it as it's just adding a command interface to Topography, which remains responsible for actually generating the islands.

This requirement should have been specified in the mods.toml, so I have now added this.
